---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      appName: debug
  template:
    metadata:
      labels:
        appName: debug
        netic.dk/opensearch-client: "true"
        sidecar.istio.io/inject: "false"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 1000
      containers:
      - name: debug-pod
        image: ghcr.io/neticdk/kubernetes-debug-image:v0.0.7
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"